services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 3000
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file: .env

  db:
    image: postgres:alpine3.14
    expose:
      - 5432

  adminer:
    image: adminer
    ports:
      - 9000:8080
