services:
  api:
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 3000
    volumes:
      - .:/src
    ports:
      - 3000:3000
    depends_on:
      - db
      - seeds
    env_file: .env

  seeds:
    build: .
    command: >
      sh -c 'if [ "${SEEDS}" = "true" ]; then python seeds/main.py; fi'
    volumes:
      - .:/seeds
    depends_on:
      - db
    env_file: .env
    restart: "no"

  db:
    image: postgres:alpine3.14
    expose:
      - 5432

  adminer:
    image: adminer
    ports:
      - 9000:8080
